name: dev
on:
  workflow_dispatch:
  push:
    branches:
    - "master"
jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        native-image-musl: 'true'
    - run: bash +x ./gradlew nativeCompile -P'enableStatic=true'
    - uses: actions/upload-artifact@v4
      with:
        name: lite-oss
        path: build/native/nativeCompile/liteoss
